# -------------------------------- AppCenter -----------------------------------
app-center: 
  # model: debug|release
  model: debug
  http:
    port: 9012
    readHeaderTimeOut: 15
    writeTimeOut: 600
    maxHeaderBytes: 1048576

# initialized server
initServerBits: 1

innerHost:
  structor: "http://structor"
  flow: "http://flow"
  polyAPI: "http://polyapi:9090"
  org: "http://org"

# import app minimum version
compatibleVersion: "0.7.3"


# ------------------------------------ Common -----------------------------------
redis:
  addrs:
    - "127.0.0.1:6379"
  username:
  password:

mysql:
  db: app_center
  host: 127.0.0.1:3306
  user: root
  password: pwd
  log: true

# comply with zap log specification
log:
  level: -1

internalNet:
  timeout: 20
  maxIdleConns: 10

# ----------------------------------- Chaos -----------------------------------------
chaos:
  model: debug
  http:
    port: 6666

# Amount of goroutine to handle tasks
workLoad: 8

# Maximum number of retries
maximumRetry: 3

# Duration of retrying
waitTime: 2

# Signal of avoiding handling multiple task
sync: false

# Custom defination
kv: 
  form-role: http://form/api/v1/form/%s/internal/apiRole/create
  form-assign: http://form/api/v1/form/%s/internal/apiRole/grant/assign/%s
  app-center: http://localhost/api/v1/app-center/initCallBack