model: debug
http:
  port: 6666

# Amount of goroutine to handle tasks
workLoad: 8

# Maximum number of retries
maximumRetry: 3

# Duration of retrying
waitTime: 2

log:
  level: -1

internalNet:
  timeout: 20
  maxIdleConns: 10

# Signal of avoiding handling multiple task
sync: false

# It works when sync is true
redis:
  addrs:
    - "127.0.0.1:6379"
  username:
  password:

kv: 
  form-role: http://form/api/v1/form/%s/internal/apiRole/create
  form-assign: http://form/api/v1/form/%s/internal/apiRole/grant/assign/%s
  app-center: http://localhost/api/v1/app-center/initCallBack
